### ISSUE TITLE
12-4 Class Meeting

### ISSUE THREAD

**Issue by spadafour** [RJP43/CitySlaveGirls#16]
We reviewed:
* Specifics of tagging articles
* Cody - worked on CSS

For Next Class:
* Everyone = Further Tagging of Articles: (again, refer to 10/30)
* Cody - more work on CSS (rip out methodology and move it to About...drop down boxes in there?)
* Rob - new system of tags

@CodyKarch @KariWomack @RJP43 

Also....
For tagging complex paragraphs containing multiple instances of attributes and connotations, here is the idea that @ebeshero and I discussed after class:

* What happens when we have both positive and negative connotations within a single block of text, and what do we do when Nell Nelson adds a break in the sentence?

`"You have a nice house," she said. "I would like to live in it. It is a nice house. The house is warm, and I like warm houses. However, your couch is too squishy and I do not like squishy couches. Nevertheless, I would still like to live in this house."`

* To take care of the connotation problem, we could have the options of `positive`, `negative`, and `mixed`(this is the new one). Then, to take care of the break, we could wrap it in some element to designate it as such, but it remains contained within the same block of speech.

`"<said who="workingGirl" ana="female"><rs type="livingConditions" subtype="MIXED">You have a nice house,<elementToDesignateInterruption>" she said. "<//elementToDesignateInterruption>I would like to live in it. It is a nice house. The house is warm, and I like warm houses. However, your couch is too squishy and I do not like squishy couches. Nevertheless, I would still like to live in this house.</rs></said>"`

* We would just need to designate what the element break would be named (I believe this is the solution we discussed).

**Comment by spadafour** [comment]
There is another issue: what happens when conversation handles lots of different topics at once?

`"I do not get paid much to work. I only get paid one penny a day. Working next to an open window is very cold, and it is hard to work knowing that I will only make a penny. Because I only earn one penny a day, my mother makes me do extra chores around the house. Seriously, what can I even do with just one cent?"`

Okay, here, we have someone talking generally about wages (`wageDesc`), but she interjects with comments that are ALSO about working conditions (`workDesc`) and living conditions (`livingCond`). We need to decide if it is okay to let `rs` elements (which contain these things as attributes) contain OTHER `rs` elements. If we did that, the it would look like this.

`"<said who="workingGirl" ana="female"><rs type="wageDesc">I do not get paid much to work. I only get paid one penny a day. <rs type="workDesc">Working next to an open window is very cold, and it is hard to work knowing that I will only make a penny.</rs> <rs type="livingDesc">"Because I only earn one penny a day, my mother makes me do extra chores around the house.</rs> Seriously, what can I even do with just one cent?</rs></said>"`

**Comment by RJP43** [comment]
Okay so here is what we will go with (using the examples from above):
I like the idea of adding in the new descriptor -- mixed to describe an `<rs>` `@subtype` that contains information that is perceived by he transcriber to be both positive and negative. The ideal way to code the `<rs>` elements would be to go with the initial gut feeling the statement give the transcriber and because we are representing an interpretation of sorts I think we should incorporate the `@resp` attribute with a `#` and your xml:id as the value. So this is how I would code that first example from above and this should be the example we refer to as we finish coding the articles this weekend:

`"<said who="workingGirl" ana="female">`
`<rs type="livingConditions" subtype="mixed" resp="#rjp">`
`You have a nice house,<rs type="interruption">" she said. "</rs>I would like to live in it. It is a nice` `house. The house is warm, and I like warm houses. However, your couch is too squishy and I do` `not like squishy couches. Nevertheless, I would still like to live in this house.</rs></said>"`

Okay for the next circumstance I am going to complicate the example a bit to show how we might used combined `<rs>` elements and multiple attribute values for a single `<rs>` `@type`.
Here it goes:

`"<said who="workingGirl" ana="female">`
`<rs type="wageDesc" subtype="negative" resp="#rjp">I do not get paid much to work. I only get` `paid one penny a day. <rs type="workDesc|workEnvir" subtype="negative" resp="#rjp">The work is` `tedious because I am working next to an open window and wearing a jacket would interfere with` `the stitching of cloaks; therefore, I am very cold while I work.</rs> 
`<rs type="livingCond" subtype="negative" resp="#rjp">"Because I only earn one penny a day, my` `mother makes me do extra chores around the house.</rs> Seriously, what can I even do with just` `one cent?</rs></said>"`

So we have the main idea of the `<said>` being about and referring multiple times to a wage description (`rs type="wageDesc"`) so we wrap the whole thing in the `<said>` element and that `rs type="wageDesc"`. Then the next sentence the way the speaker is mixing conversation about the working environment and the kind of work being done that calls for the double values in the single `<rs>` `@type` (`rs type="workDesc|workEnvir"`). Then in the second to the last line I only assign the one `@type="livingCond"` even though there is specific mention of her wage before describing her home life because this `<rs>` is already sitting inside of the  `rs type="wageDesc"`

Hope that clear things up. Any questions or concerns with this way of doing things? @ebeshero @spadafour @CodyKarch @KariWomack

**Comment by ebeshero** [comment]
This looks sensible to me! I wonder if there's a simpler way to deal with `@resp`: The `@resp` attribute shows who's making the call, which might aid in later review if, say, Rob starts to see a pattern in the files he's marking, or Becca wants to look over the collection of files to see how Kari tended to mark something, Do you anticipate having multiple team members adding interpretive code to each article? Or are you each taking on assignments to mark an entire article yourselves? If you are each writing this code over a whole article, I would recommend including just one line of code up in the TEI header to indicate your role in this file. This is typically done in a TEI respStmt up where you list which editors have worked on this document and the ping us to describe the kind of work they did. Doing this with a respStmt just once at the top of the file could save you some time! 

If this sounds like a good idea, I'll look up some examples and show you how we do respStmt for something similar in the Mitford project. It ONLY makes sense if each editor is responsible for adding interpretive markup to an entire file.

**Comment by RJP43** [comment]
@ebeshero I can think of instances where I may want to add interpretations or future editors might want to add interpretations to the markup of this year's editors that is why I was suggesting the `@resp`; however, everyone as I mentioned in class on Friday you should edit the TEI header of the articles you are working on to include your contributions there is a `<respStmt>` commented out in all of the headers that you could very well un-comment or use as a format reference to make your own `<respStmt>` referring to the work you are doing on the article that includes your xml:id.
