### ISSUE TITLE
Tagging Question

### ISSUE THREAD

**Issue by CodyKarch** [RJP43/CitySlaveGirls#18]
Hey @RJP43 I was wondering two things: 1. You want us to put tags in the headlines, right? 2. How should we approach quoting when it is presented inside of a box image? My article contains this on page two, if you check the PDF of the newspaper.
https://github.com/RJP43/CitySlaveGirls-ChicagoDailyTimes1888/blob/master/ChicagoTimes_CSG_PDFandOldXML/Nell_Nelson_8-8-1888.pdf

**Comment by RJP43** [comment]
No tagging in headlines because it is out of context and will only add duplicates of stuff we tag within the article @CodyKarch @KariWomack @spadafour (I'm pretty sure I said this Friday, but okay maybe not)

And if the text is inside a "box image" as a representation of a sign or contract/document simply put it in its own `<p>` tag and then leave a comment tag with your initials and the date saying how the item is represented in the text.

**Comment by CodyKarch** [comment]
So if it is another level of quotation being representative of a sign, I put the quote inside the `<p>` tag?

**Comment by RJP43** [comment]
yea... the `<p>` is structural markup so structural markup will always sit outside of any contextual markup
