### ISSUE TITLE
Presentation Feedback

### ISSUE THREAD

**Issue by spadafour** [RJP43/CitySlaveGirls#20]
Hey, Dickinson Group, let us know what you think!

**Comment by RJP43** [comment]
javascript suggestion for articles: toggling grammatical markup and toggling for quotes (on two levels choosing a range of colors that look good together)

css: for the `<said>` box-model (what looks best? coloring the whole box or just the border/outline?) each said will get their own color

need colors for each nouns and adjectives --- need colors that correspond for all of this!

**Comment by ebeshero** [comment]
Here's a link to the Dickinson group's issue page for project comments: https://github.com/ebeshero/EmilyDickinson16/issues/25

**Comment by RJP43** [comment]
@spadafour @ebeshero @KariWomack @CodyKarch 

How does this look for an example: 
example: `A <seg><w type="adj" ana="pale">pale-faced</w> <w type="noun" ana="workingGirl">Hannah</w></seg> refused to stitch the <w ype="noun">dress</w>. The <seg><w type="adj" ana="lazy">lazy</w> <w type="noun" ana="foreperson">foreman</w></seg> yelled at <w type="noun" ana="workingGirl">her</w>, "You are the <seg><w type="adj" ana="lazy">laziest</w> <w type="noun" ana="workingGirl">stitcher</w></seg>".`

**Comment by blawrence719** [comment]
I'm not sure if you guys are actually planning on doing this, but I know that @RJP43 had talked about how she was interested in how males vs females would categorize/tag everything differently and I think that this would be interesting and something to incorporate in a page similar to the Dickinson team's conclusion page. I think it's especially interesting because you're working with articles about the working conditions for women and it would be engaging to see the different ways that your group would tag things. I think you could talk about your process with everything and all the struggles you came across in figuring out how to code everything - everything that @spadafour had talked about at the beginning of your presentation. Even if you don't fully run with the idea of male vs female interpretations, a small analysis could be interesting.

**Comment by brookestewart** [comment]
I think it would be a good idea to document your thought process as you worked through the tagging differences and explain how you came up with a concrete set of tags - just a short explanation, possibly in a conclusion page. I agree with @blawrence719  that it would be interesting to show the different thought processes and why everyone didn't immediately agree on how things should be coded. One thing that stood out to me was the layout of the graphs. I think it's really neat, organized, and easy to understand. Definitely a strong point!

**Comment by nlottig94** [comment]
I really like what you guys are doing with the page.  I also really like how @RJP43 and @spadafour discuss issues they have with coding.  Being in the room on Thursday evening and Friday morning when you were discussing how you should go about tagging the articles is a very interesting issue.  It made me think about how different opinions are depending on how the articles are read or what a person really wants to pull from the data presented.  I also liked how thought-provoking it was just learning about the different TEI tags that you all could throughout your articles.  A lot of critical thinking has gone into your project and should definitely be documented!!!!  I think it would be really cool if you guys could somehow analyze the data and compare the differences between how males and females read Nell's articles!  Maybe in some sort of chart or graph?

I can't wait to see the page when it is finished!!  Good luck!!
