### ISSUE TITLE
Where are we going?

### ISSUE THREAD

**Issue by RJP43** [RJP43/CitySlaveGirls#47]
@spadafour 

Let's touch base here...

Where are we in getting the Barkley Publication updated with `<p>` tags?  
What semantic markup have we decided to remove from the articles? And what did we decide to add?  (ARE WE DOING VERBS? We want to remove the adjective markup except on archetypes and use of possesive pronouns, right?)  
Once the Barkley Publications are complete I think we could do a bulk transcription of the articles by coping over the Barkley text and running through editing the differences? Do we want to do this? Can we think of a clever way to markup up what is added/subtracted?  Is that useful markup for what we plan on creating visually?   
What do we plan on creating visually?   
Let's come up with a solid new research question... and I think we agreed it would be based on versioning?

**Comment by RJP43** [comment]
There are a series of things to fix based off of last semester comments... lets come up with a plan to attack those issues as well. We can do some of this in person this week, but at least this issue gives us a starting point and place to jot down ideas.

**Comment by RJP43** [comment]
Also we have some broken links on our site ... damn!

**Comment by spadafour** [comment]
We're about 1/4 of the way through adding <p> tags to the barkley publications, it'll take a solid free night to finish that out, nothing too time consuming.

Are we doing verbs? Maybe? I think priority #1 would be focusing on finding differences between the originals and the Barkley texts. What was that website (I think?) that Dr. B showed us last year that compared and contrasted two uploaded texts? Do you remember that/ do you think we could use that at all? Otherwise, we could compare string lengths of paragraphs to narrow down what changed from the different publications, and figure out something more precise from there.

Visually, I'm not sure. Do you have any ideas?

What links were broken?

**Comment by RJP43** [comment]
# Meeting 3/16:

- [ ] Fix last semester issues --- curly quote formatting check out CSS formatting on Mitford (?)

- [ ] mark variation texts using Barkley transcriptions and editing where original articles change using the `<app>` `<rdg>` -  Variant Mark-Up Reference: https://docs.google.com/document/d/1r-8NGPJL1pZ20pnfvoX5OT0DkcDi-NBp5urJiZwx1sY/edit# 

- [ ] continue marking proper nouns (people and companies)

- [ ] mark streets & addresses (locations in general)

**investigate automatic parts of speech markup **

- [ ] continue marking possessive pronouns and `<seg>` with noun or related words that are being possessed or possessing

- [ ] keep the said elements with attributes to grab who and how much speech each archetype gets

- [ ] cut the "all adjective markup" that grabs nouns and adjectives related in the previously marked up articles

- [ ] edit codebook and schematron according to new elements/attributes

**Comment by RJP43** [comment]
We have started the variation markup which can be found in [this article](https://github.com/RJP43/CitySlaveGirls/blob/master/Nelson_CSG/CSG_XML/1888-08-19-ChTimes.xml) and we have ackled one issue from last semester regarding curly quotes. Still some work here, but I am closing this issue and will add these few things to the project check list in a later issue!
