### ISSUE TITLE
Official Submission Spring 2016

### ISSUE THREAD

**Issue by spadafour** [RJP43/CitySlaveGirls#65]
@ebeshero @ghbondar 
@RJP43 and I are officially submitting our [project for grading](http://nelson.newtfire.org/index.html). This is what we were able to produce in the time allotted; there are aspects of this site that we know need to be improved. Since this project is ongoing, these are the things we plan to continue with in the future:

-We could not implement PHP within the reading views in time
-We did not get javascript working on the single article ready for versioning, [8/19](http://nelson.newtfire.org/1888-08-19.html)
-We have yet to highlight our grammar markup using javascript that links the network analysis to readable text
-We have yet to map locations

What we have done:
-Complete overhaul of the site
-Complete codebook
-Complete XML on all Chicago Times articles
-CSS and layout overhaul
-Multiple reading Views
-Grammatical Network Data Visualization

**Comment by RJP43** [comment]
*complete overhaul of the site writeups

**Comment by ebeshero** [comment]
@spadafour @RJP43 Thanks for the submission notice! Before I grade this, I want to draw your attention to a site rendering problem: Open your pages in Firefox or a browser other than Chrome and look at your apostrophes. There's a UTF-8 encoding problem and (just as importantly), a related problem with w3c Validation. 

Here's what happens when I go to validate your site: https://validator.w3.org/nu/?doc=http%3A%2F%2Fnelson.newtfire.org%2F

You want to alter the top lines of those HTML pages: Part of the issue here is that we're working at the PSC with an Apache server that only serves up HTML as HTML (and not HTML with the XML line at the top). If you don't use that line you want to move that utf-8 character encoding notice into a meta tag. Here's an example from a newtfire page: http://newtfire.org/dh/explainHTML.html

I'd really like to see your project site be submitted without validation errors like this, so I hope you two can quickly clean this up to leave your project in a tidy place for grading.

**Comment by spadafour** [comment]
Okay, @ebeshero , all pages are now valid.

That is, all pages but the ones with network graphs on them; the validator does not like the s, and I don't know why.

But everything else is valid now, and the sag is at least visually there.
